spring.application.name=minichatgpt

spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.username=elastic
spring.elasticsearch.password=password


spring.ai.vectorstore.elasticsearch.index-name=documents
spring.ai.vectorstore.elasticsearch.initialize-schema=true

llm.providers=ollama

minichatgpt.ollama.endpoint=http://localhost:11434
minichatgpt.ollama.chat-model=gemma4:e4b
minichatgpt.ollama.embedding-model=qwen3-embedding:0.6b

minichatgpt.open-ai.endpoint=http://localhost:8081
minichatgpt.open-ai.chat-model=Qwen3.5-9B-Q5_K_M.gguf
minichatgpt.open-ai.embedding-model=qwen3-embedding:0.6b