spring.application.name=minichatgpt

spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.username=elastic
spring.elasticsearch.password=password

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.model=qwen3-embedding:0.6b
spring.ai.ollama.chat.model=gemma4:e4b

spring.ai.vectorstore.elasticsearch.index-name=documents
spring.ai.vectorstore.elasticsearch.initialize-schema=true